### ISSUE TITLE
Possible addition for selection order support?

### ISSUE THREAD

**Issue by Sxcerino** [uzysjung/UzysAssetsPickerController#34]
Thanks for the great library, much appreciated.

I noticed that the images are returned in the order from photo album(oldest -> newest) rather than the selection order, which might get confusing at times. Would it be possible to add this as a feature?

As an aside - currently there isn't an easy way to customize the color of the header (navigationTop and lineView), wondering if these should be made public or configurable?

Thank you again.

**Comment by uzysjung** [comment]
1. yes very easy. you just change NSEnumerationReverse -> NSEnumerationForward in UzysAssetsPickerController.m.
2. you can customize using UzysAssetsPickerController.xib

**Comment by Sxcerino** [comment]
1. Sorry perhaps I didn't get my point across. 
I don't mean the way the photos are displayed in the picker, I mean the selection order dictated by the user upon selecting them in the picker and stored in the assets array returned with didFinishPickingAssets.
e.g. if there are photos A B C D and the user selects B then D then A, that's the order that should be reflected.

2. Ah yes, my mistake, sorry missed that.

Thank you

**Comment by uzysjung** [comment]
I understood. that is not difficult. but If I have to add this feature I'd like to add this feature with UI change such as number marked.

**Comment by Sxcerino** [comment]
Thanks for the quick replies.
Out of curiosity - when you say it's not difficult to implement, would you happen to have the method that needs to be added for this to work? If not I'll try tinkering with it but guidance would be appreciated :P

Many thanks,

**Comment by uzysjung** [comment]
1. create array property in order to save assets --> @property (nonatomic,strong) NSMutableArray pSelectedArr;

2. add assets to the array when you pick up. 

- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
   // insert Asset
   [self.pSelectedArr addObject: [self.assets objectAtIndex:indexPath.item]];
    [self setAssetsCountWithSelectedIndexPaths:collectionView.indexPathsForSelectedItems];
}

- (void)collectionView:(UICollectionView *)collectionView didDeselectItemAtIndexPath:(NSIndexPath *)indexPath
{
 //remove Asset
   self.pSelectedArr removeObject:self.assets  [self.assets objectAtIndex:indexPath.item]];
    [self setAssetsCountWithSelectedIndexPaths:collectionView.indexPathsForSelectedItems];
}


3. return the array when you 've done. ->   (void)finishPickingAssets 
you use pSelectedArr instead of local variable mutable array assets
